export const ElementType = Object.freeze({
    "Text": 0,
    "Image": 1,
    "Code128Barcode": 2,
    "Code39Barcode": 3,
    "Code25Barcode": 4,
    "Code93Barcode": 5,
    "Code11Barcode": 6,
    "Gs1DataBarBarcode": 7,
    "Iata25Barcode": 8,
    "MsiBarcode": 9,
    "StackedGs1DataBarBarcode": 10,
    "AztecBarcode": 11,
    "DataMatrixBarcode": 12,
    "MacroPdf417Barcode": 13,
    "Pdf417Barcode": 14,
    "QrCode": 15,
    "PageNumbering": 16,
    "Line": 17,
    "Rectangle": 18
});