export const pageSizeName = Object.freeze({
    "A3" :"A3",
    "A4" :"A4",
    "A5" :"A5",
    "A6" :"A6",
    "B3" :"B3",
    "B4" :"B4",
    "B5" :"B5",
    "B5JIS" :"B5JIS",
    "DoublePostcard" :"DoublePostcard",
    "Envelope10" :"Envelope10",
    "EnvelopeDL" :"EnvelopeDL",
    "EnvelopeC5" :"EnvelopeC5",
    "EnvelopeB5" :"EnvelopeB5",
    "EnvelopeMonarch" :"EnvelopeMonarch",
    "Executive" :"Executive",
    "Legal" :"Legal",
    "Folio" :"Folio",
    "Letter" :"Letter",
    "Postcard" :"Postcard",
    "PRC16K" :"PRC16K",
    "PRC32K" :"PRC32K",
    "Quatro" :"Quatro",
    "Statement" :"Statement",
    "Tabloid" :"Tabloid"
});